config/routes.rb
VirtualCloset::Application.routes.draw do
  root to: 'users#new'
  match '/items', to: 'closet#create', via: :post
  resources :users
  resources :outfits
  resources :closet
  resources :sessions, only: [:new, :create, :destroy]
  resources :users do
    resources :outfits
  end
  
  

   root :to => 'closet#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :items
  attr_accessible :name
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :outfits, through: :OutfitItems
  has_many :OutfitItems
  attr_accessible :name, :category_id, :user_id, :pic
  has_attached_file :pic
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  has_many :OutfitItems
  has_many :items, through: :OutfitItems
  belongs_to :user
  attr_accessible :name, :user_id
end

app/models/outfit_item.rb
class OutfitItem < ActiveRecord::Base
  belongs_to :outfit
  belongs_to :item
  attr_accessible :outfit_id, :item_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :outfits
  has_many :items
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :name,		:presence 	=> true,
  					:length		            => { :maximum => 50 }
  validates :email,		:presence		=> true,
  					:format		            => { :with => email_regex },
           	:uniqueness 	        => { :case_sensitive => false }

  validates :password, 	:presence => true,
  	   			:confirmation 	      => true,
  					:length			          => { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
  	encrypted_password == encrypt(submitted_password)
  end


  # class method that checks whether the user's email and submitted_password are valid
  def self.authenticate(email, submitted_password)
  	user = find_by_email(email)

   	return nil if user.nil?
   	return user if user.has_password?(submitted_password)
  end


  private
  	def encrypt_password
  		# generate a unique salt if it's a new user
  		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
  	
  		# encrypt the password and store that in the encrypted_password field
  		self.encrypted_password = encrypt(password)
  	end

  	# encrypt the password using both the salt and the passed password
  	def encrypt(pass)
  		Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
  	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/closet_controller.rb
class ClosetController < ApplicationController
  def index
  	 @user = current_user
  	 @items = current_user.items
  	 @item = Item.new
     @outfits = current_user.outfits
      #render :text => @items
  end

  

  def create
 	 # render text: params[:item]
 	@item = Item.new(params[:item])

 	if @item.save
      redirect_to closet_index_path, notice: 'item was successfully created.'
    else
      redirect_to closet_index_path, notice: 'item was not created.'
    end

  end
end

app/controllers/outfit_controller.rb
class OutfitController < ApplicationController
  def create
     # render text: params

    @outfit = Outfit.new(params[:outfit])
    
  	  if @outfit.save
        # render text: "saved"
        # render :text => params[:item] 
          outfitItems = params[:item]
          outfitItems.each do |i|
            OutfitItem.create(:outfit_id => @outfit.id, :item_id => i)
          end
    	   	redirect_to closet_index_path, notice:"outfit saved!"	
      else
        # render text: "not saved"
         render 'new', notice: 'Product not created'
      end
  end
  

  def show
    # render :text => 'show'
    # render :text => params[:id]
      @outfitItems = OutfitItem.where("outfit_id =" +  params[:id])
      @Outfit = Outfit.find(params[:id])

  end

  def update
  end

  def delete
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  def create
     # render text: params

   # raise "foo"
   # return
    @outfit = Outfit.new(params[:outfits])

    #render json: @outfit
    #return

  	  if @outfit.save
        # render text: "saved"
        # render :text => params[:item] 
          outfitItems = params[:item]
          outfitItems.each do |i|
            OutfitItem.create(:outfit_id => @outfit.id, :item_id => i)
          end
    	   	redirect_to closet_index_path, notice:"outfit saved!"	
      else
        # render text: "not saved"
         render 'new', notice: 'Product not created'
      end
  end
  

  def show
    # render :text => 'show'
    # render :text => params[:id]
   
     @outfit = current_user.outfits.find(params[:id])
     @outfitItems = @outfit.OutfitItems

  end

  def update
  end

  def delete
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.authenticate(params[:session][:email], params[:session][:password])

  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination."
  		render :new
  	else
  		sign_in user
  		redirect_to closet_index_path
      #redirect_to user
  		
  	end

  end

  def destroy
  	sign_out
  	redirect_to signin_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  @users = User.all
  end

  def new
  	@user = User.new
  end

  def create
   @user = User.new(params[:user])
  	# render text: params[:user]
    if @user.save
      sign_in(@user)
      redirect_to @user, notice: 'User was successfully created.'
    else
      # render :text => "here"
      render action: "new"
    end
  end

  def show
    #render :text => session[:user_id]
  	#@user = User.find(params[:id])
    @user = current_user
  	
  	#@items = User.find(params[:id]).items.all
  	#@outfits = User.find(params[:id]).outfits.all
  	
  		
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closet_helper.rb
module ClosetHelper
end

app/helpers/outfit_helper.rb
module OutfitHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    session[:user_id] = user.id
    self.current_user = user
  end
  
  # setter method
  def current_user=(user)
    @current_user = user
  end

  # getter method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    self.current_user = nil
  end

  def current_user?(user)
    user == current_user 
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/closet/index.html.erb
  <div id="topNav">
  <div id="intro">Create your daily outfit and share with friends!</div>
  <ul>
      <li><a href=#>My account</a></li>
      <li><a href=#>Log out</a></li>
  </ul> 
</div>
<div class="clear"></div>
<div id="titleNav">
  <ul>
    <li id="title">Virtual Closet</li> 
    <li id="image1"><%=  image_tag("outfits.jpg", width:"400")%></li>
  </ul>
  <p id="desc"> Drag multiple items from the closet to the center canvas,</br> and click save button to save the outfit</p>
   
</div>
<div class="clear"></div>




<!--<%= @current_user.id %> -->

<div id="closet">

  <h2 class="ui-widget-header"><%= @user.name %>'s Closet</h2>
  
  <div id="catalog">
    <ul >
      <li><a href='#tab1'>Top</a></li>
      <li><a href='#tab2'>Bottom</a></li>
      <li><a href='#tab3'>Shoes</a></li>
      <li><a href='#tab4'>Others</a></li>
    </ul>
    
    <div id="tab1"> 
      <ul type=none>
        <% @items.each do |item| %>
          <% if item.category_id==1 %>
            <li><span id="<%= item.id %>"></span><%=  image_tag(item.pic.url, width:"100")%></li>

          <%  end %>
        <% end %>

      </ul>
    </div>

    <div id='tab2'>
      <ul type=none>
        <% @items.each do |item| %>
          <% if item.category_id==2 %>
            <li><span id="<%= item.id %>"></span><%= image_tag(item.pic.url, width:"100") %></li>
          <%  end %>
        <% end %>
    </ul>
    </div>

    <div id='tab3'>
      <ul type=none>
        <% @items.each do |item| %>
          <% if item.category_id==3 %>
            <li><span id="<%= item.id %>"></span><%= image_tag(item.pic.url, width:"100") %></li>
          <%  end %>
        <% end %>
    </ul>
    </div>   

    <div id='tab4'>
      <ul type=none>
        <% @items.each do |item| %>
          <% if item.category_id==4 %>
            <li><span id="<%= item.id %>"></span><%= image_tag(item.pic.url, width:"100") %></li>
          <%  end %>
        <% end %>
    </ul>
    </div>
 
  </div><!--end of catalog -->

  <div id="add_new">
    <h2 class="ui-widget-header">Add new Items</h2>

    <div id="addForm">
      <%= simple_form_for @item, :html=>{:multipart=>true} do |i| %>
        <%= i.hidden_field :user_id, :value=>@current_user.id %>
        <%= i.file_field :pic %>
        <%= i.input :name, label:'Item name' %>
        <%= i.association :category  %>  
        <%= i.submit %>
      <% end %>
    </div><!--end of addForm -->
  </div><!--end of add_new -->
</div><!--end of closet-->
 
<div id="canvas">
  <h2 class="ui-widget-header">Outfit Canvas</h2>
  <div id="outfit">
    <ol type=none id="outfit_list">
      <li class="placeholder">Add your clothes here</li>
    </ol>
    
    <%= form_for([@user, @user.outfits.new]) do |f| %>
    <!--
    <form action="/user/[params :id]/outfits" method="post">
    -->
      <div id="o_name">
        <label for="name">Outfit Name</label>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
        <input type="hidden" name="outfits[user_id]" value="<%= @current_user.id %>" />
        <input type="text" name="outfits[name]">
       
        <input id="save" type="submit" value="Save" name="submit">
      </div>
      <button id="submit" type="button">Add Outfit</button>
    <% end %>
  </div>
</div>

<div id="recent-outfit">
    <h2 class="ui-widget-header">Recent Outfits</h2>
    <div id="recent-outfitlist">
      <% @outfits.each do |f| %>
        <p><%= link_to f.name,  "outfits/#{f[:id]}" || outfit_path(f[:id]) %></p>
      <% end %>
    </div>
</div>
<div id="clear"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VirtualCloset</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>


</body>
</html>

app/views/outfit/show.html.erb
<h1>Outfit: <%=@Outfit.name%></h1>
<ul>
<% @outfitItems.each do |o| %>
	<!--<%= o.item_id%>-->
	
	<li>
		<div class="item-name">
			<h3><%= o.item.category.name %></h3>
			<%=  image_tag(o.item.pic.url, width:"100")%>
		</div>
	</li>
	<% end %>
</ul>

app/views/outfits/show.html.erb
<h1>Outfit: <%= @outfit.name %></h1>
<ul>
<% @outfitItems.each do |o| %>
	<!--<%= o.item_id%>-->
	
	<li>
		<div class="item-name">
			<h3><%= o.item.category.name %></h3>
			<%=  image_tag(o.item.pic.url, width:"100")%>
		</div>
	</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<h1>Register</h1>
<%= simple_form_for(@user) do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>

<h1>Login</h1>

<% if flash[:error] %>
	<p><%= flash[:error] %></p>
<% end %>

<%= simple_form_for(:session, :url => sessions_path) do |f| %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.button :submit %>
<% end %>

app/views/users/show.html.erb
<h1>this is user show page </h1>


<h1>User <%= @user.id %></h1>

<h2>User information</h2>
<%= @user.name %>&nbsp;&nbsp; <%= @user.email %><br/>

<h2>Outfits</h2>
<% @user.outfits.each do |o| %>
  <p>
    <strong>outfit name</strong>
    <%= o.name %>
  </p>
<% end %>

<h2>Items</h2>
<% @user.items.each do |i| %>
  <p>
    <strong>outfit name</strong>
    <%= i.name %>
  </p>
<% end %>